// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gity/point-system/config"
	web2 "github.com/gity/point-system/controllers/web"
	"github.com/gity/point-system/controllers/web/presenter"
	"github.com/gity/point-system/entities"
	"github.com/gity/point-system/frameworks/web"
	"github.com/gity/point-system/frameworks/web/middleware"
	"github.com/gity/point-system/gateways/datasource/dspostgresimpl"
	"github.com/gity/point-system/gateways/infra/infraemail"
	"github.com/gity/point-system/gateways/infra/infralogger"
	"github.com/gity/point-system/gateways/infra/infrapassword"
	"github.com/gity/point-system/gateways/infra/infrapostgres"
	"github.com/gity/point-system/gateways/infra/infrastorage"
	"github.com/gity/point-system/gateways/repository/category"
	"github.com/gity/point-system/gateways/repository/daily_bonus"
	"github.com/gity/point-system/gateways/repository/friendship"
	"github.com/gity/point-system/gateways/repository/lottery_tier"
	"github.com/gity/point-system/gateways/repository/point_batch"
	"github.com/gity/point-system/gateways/repository/product"
	"github.com/gity/point-system/gateways/repository/qrcode"
	"github.com/gity/point-system/gateways/repository/session"
	"github.com/gity/point-system/gateways/repository/system_settings"
	"github.com/gity/point-system/gateways/repository/transaction"
	"github.com/gity/point-system/gateways/repository/transfer_request"
	"github.com/gity/point-system/gateways/repository/user"
	"github.com/gity/point-system/gateways/repository/user_settings"
	"github.com/gity/point-system/usecases/interactor"
	"github.com/gity/point-system/usecases/service"
)

// Injectors from wire.go:

// InitializeApp は Wire を使ってアプリケーションの依存関係を自動注入する
func InitializeApp(cfg *config.Config) (*AppContainer, error) {
	routerConfig := ProvideRouterConfig(cfg)
	timeProvider := web.NewSystemTimeProvider()
	infrapostgresConfig := ProvideDBConfig(cfg)
	db, err := infrapostgres.NewPostgresDB(infrapostgresConfig)
	if err != nil {
		return nil, err
	}
	userDataSource := dspostgresimpl.NewUserDataSource(db)
	logger := infralogger.NewLogger()
	userRepository := user.NewUserRepository(userDataSource, logger)
	sessionDataSource := dspostgresimpl.NewSessionDataSource(db)
	sessionRepository := session.NewSessionRepository(sessionDataSource, logger)
	passwordService := infrapassword.NewBcryptPasswordService()
	authInputPort := interactor.NewAuthInteractor(userRepository, sessionRepository, passwordService, logger)
	authPresenter := presenter.NewAuthPresenter()
	authController := web2.NewAuthController(authInputPort, authPresenter)
	gormTransactionManager := ProvideGormTransactionManager(db)
	transactionDataSource := dspostgresimpl.NewTransactionDataSource(db)
	transactionRepository := transaction.NewTransactionRepository(transactionDataSource, logger)
	idempotencyKeyDataSource := dspostgresimpl.NewIdempotencyKeyDataSource(db)
	idempotencyKeyRepository := transaction.NewIdempotencyKeyRepository(idempotencyKeyDataSource, logger)
	friendshipDataSource := dspostgresimpl.NewFriendshipDataSource(db)
	friendshipRepository := friendship.NewFriendshipRepository(friendshipDataSource, logger)
	pointBatchDataSource := dspostgresimpl.NewPointBatchDataSource(db)
	pointBatchRepositoryImpl := point_batch.NewPointBatchRepository(pointBatchDataSource)
	pointTransferInteractor := interactor.NewPointTransferInteractor(gormTransactionManager, userRepository, transactionRepository, idempotencyKeyRepository, friendshipRepository, pointBatchRepositoryImpl, logger)
	pointPresenter := presenter.NewPointPresenter()
	pointController := web2.NewPointController(pointTransferInteractor, pointPresenter)
	friendshipInputPort := interactor.NewFriendshipInteractor(friendshipRepository, userRepository, logger)
	userQueryInputPort := interactor.NewUserQueryInteractor(userRepository, logger)
	friendPresenter := presenter.NewFriendPresenter()
	friendController := web2.NewFriendController(friendshipInputPort, userQueryInputPort, friendPresenter)
	qrCodeDataSource := dspostgresimpl.NewQRCodeDataSource(db)
	qrCodeRepository := qrcode.NewQRCodeRepository(qrCodeDataSource, logger)
	qrCodeInputPort := interactor.NewQRCodeInteractor(qrCodeRepository, pointTransferInteractor, logger)
	qrCodePresenter := presenter.NewQRCodePresenter()
	qrCodeController := web2.NewQRCodeController(qrCodeInputPort, qrCodePresenter)
	transferRequestDataSource := dspostgresimpl.NewTransferRequestDataSource(db)
	transferRequestRepository := transfer_request.NewTransferRequestRepository(transferRequestDataSource, logger)
	transferRequestInputPort := interactor.NewTransferRequestInteractor(transferRequestRepository, userRepository, pointTransferInteractor, logger)
	transferRequestPresenter := presenter.NewTransferRequestPresenter()
	transferRequestController := web2.NewTransferRequestController(transferRequestInputPort, userQueryInputPort, transferRequestPresenter)
	dailyBonusDataSource := dspostgresimpl.NewDailyBonusDataSource(db)
	dailyBonusRepositoryImpl := daily_bonus.NewDailyBonusRepository(dailyBonusDataSource)
	systemSettingsDataSource := dspostgresimpl.NewSystemSettingsDataSource(db)
	systemSettingsRepositoryImpl := system_settings.NewSystemSettingsRepository(systemSettingsDataSource)
	lotteryTierDataSource := dspostgresimpl.NewLotteryTierDataSource(db)
	lotteryTierRepositoryImpl := lottery_tier.NewLotteryTierRepository(lotteryTierDataSource)
	dailyBonusInteractor := interactor.NewDailyBonusInteractor(dailyBonusRepositoryImpl, userRepository, transactionRepository, gormTransactionManager, systemSettingsRepositoryImpl, pointBatchRepositoryImpl, lotteryTierRepositoryImpl, logger)
	dailyBonusPresenter := presenter.NewDailyBonusPresenter()
	dailyBonusController := web2.NewDailyBonusController(dailyBonusInteractor, dailyBonusPresenter)
	analyticsDataSource := dspostgresimpl.NewAnalyticsDataSource(db)
	adminInputPort := interactor.NewAdminInteractor(gormTransactionManager, userRepository, transactionRepository, idempotencyKeyRepository, pointBatchRepositoryImpl, analyticsDataSource, logger)
	adminPresenter := presenter.NewAdminPresenter()
	adminController := web2.NewAdminController(adminInputPort, adminPresenter)
	productDataSource := dspostgresimpl.NewProductDataSource(db)
	productRepository := product.NewProductRepository(productDataSource, logger)
	productManagementInputPort := interactor.NewProductManagementInteractor(productRepository, logger)
	productExchangeDataSource := dspostgresimpl.NewProductExchangeDataSource(db)
	productExchangeRepository := product.NewProductExchangeRepository(productExchangeDataSource, logger)
	productExchangeInteractor := interactor.NewProductExchangeInteractor(gormTransactionManager, productRepository, productExchangeRepository, userRepository, transactionRepository, pointBatchRepositoryImpl, logger)
	productController := web2.NewProductController(productManagementInputPort, productExchangeInteractor, logger)
	categoryDataSource := dspostgresimpl.NewCategoryDataSource(db)
	categoryRepository := category.NewCategoryRepository(categoryDataSource, logger)
	categoryManagementInputPort := interactor.NewCategoryManagementInteractor(categoryRepository, logger)
	categoryController := web2.NewCategoryController(categoryManagementInputPort, logger)
	userSettingsRepository := user_settings.NewUserSettingsRepository(userDataSource, logger)
	archivedUserDataSourceImpl := dspostgresimpl.NewArchivedUserDataSource(db)
	archivedUserRepository := user_settings.NewArchivedUserRepository(archivedUserDataSourceImpl, logger)
	emailVerificationDataSourceImpl := dspostgresimpl.NewEmailVerificationDataSource(db)
	emailVerificationRepository := user_settings.NewEmailVerificationRepository(emailVerificationDataSourceImpl, logger)
	usernameChangeHistoryDataSourceImpl := dspostgresimpl.NewUsernameChangeHistoryDataSource(db)
	usernameChangeHistoryRepository := user_settings.NewUsernameChangeHistoryRepository(usernameChangeHistoryDataSourceImpl, logger)
	passwordChangeHistoryDataSourceImpl := dspostgresimpl.NewPasswordChangeHistoryDataSource(db)
	passwordChangeHistoryRepository := user_settings.NewPasswordChangeHistoryRepository(passwordChangeHistoryDataSourceImpl, logger)
	fileStorageService, err := ProvideFileStorageService()
	if err != nil {
		return nil, err
	}
	emailService := ProvideEmailService(logger)
	userSettingsInputPort := interactor.NewUserSettingsInteractor(gormTransactionManager, userRepository, userSettingsRepository, archivedUserRepository, emailVerificationRepository, usernameChangeHistoryRepository, passwordChangeHistoryRepository, fileStorageService, passwordService, emailService, logger)
	userSettingsPresenter := presenter.NewUserSettingsPresenter()
	userSettingsController := web2.NewUserSettingsController(userSettingsInputPort, userSettingsPresenter)
	authMiddleware := middleware.NewAuthMiddleware(authInputPort)
	csrfMiddleware := middleware.NewCSRFMiddleware()
	router := ProvideRouter(routerConfig, timeProvider, authController, pointController, friendController, qrCodeController, transferRequestController, dailyBonusController, adminController, productController, categoryController, userSettingsController, authMiddleware, csrfMiddleware)
	appContainer := &AppContainer{
		Router:          router,
		DB:              db,
		DailyBonusUC:    dailyBonusInteractor,
		PointBatchRepo:  pointBatchRepositoryImpl,
		UserRepo:        userRepository,
		TransactionRepo: transactionRepository,
		TxManager:       gormTransactionManager,
		Logger:          logger,
		TimeProvider:    timeProvider,
	}
	return appContainer, nil
}

// wire.go:

func ProvideDBConfig(cfg *config.Config) *infrapostgres.Config {
	return &infrapostgres.Config{
		Host:     cfg.Database.Host,
		Port:     cfg.Database.Port,
		User:     cfg.Database.User,
		Password: cfg.Database.Password,
		DBName:   cfg.Database.DBName,
		SSLMode:  cfg.Database.SSLMode,
		Env:      cfg.Server.Env,
	}
}

func ProvideRouterConfig(cfg *config.Config) *web.RouterConfig {
	return &web.RouterConfig{
		Env:             cfg.Server.Env,
		AllowedOrigins:  cfg.Security.AllowedOrigins,
		MaxUploadSizeMB: cfg.Server.MaxUploadSizeMB,
	}
}

func ProvideFileStorageService() (service.FileStorageService, error) {
	return infrastorage.NewLocalStorage(&infrastorage.Config{
		BaseDir:   "./uploads/avatars",
		BaseURL:   "/uploads/avatars",
		MaxSizeMB: 20,
	})
}

func ProvideEmailService(logger entities.Logger) service.EmailService {
	return infraemail.NewConsoleEmailService(logger)
}

func ProvideRouter(
	cfg *web.RouterConfig,
	tp web.TimeProvider,
	auth *web2.AuthController,
	point *web2.PointController,
	friend *web2.FriendController, qrcode2 *web2.QRCodeController,
	transferReq *web2.TransferRequestController,
	dailyBonus *web2.DailyBonusController,
	admin *web2.AdminController, product2 *web2.ProductController, category2 *web2.CategoryController,
	settings *web2.UserSettingsController,
	authMW *middleware.AuthMiddleware,
	csrfMW *middleware.CSRFMiddleware,
) *web.Router {
	r := web.NewRouter(cfg, tp)
	r.RegisterRoutes(
		auth, point, friend, qrcode2, transferReq,
		dailyBonus, admin, product2, category2, settings,
		authMW, csrfMW,
	)
	return r
}
