// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/qrcode.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/qrcode.go -destination=internal/domain/mock/mock_qrcode_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/gity/point-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQRCodeRepository is a mock of QRCodeRepository interface.
type MockQRCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQRCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockQRCodeRepositoryMockRecorder is the mock recorder for MockQRCodeRepository.
type MockQRCodeRepositoryMockRecorder struct {
	mock *MockQRCodeRepository
}

// NewMockQRCodeRepository creates a new mock instance.
func NewMockQRCodeRepository(ctrl *gomock.Controller) *MockQRCodeRepository {
	mock := &MockQRCodeRepository{ctrl: ctrl}
	mock.recorder = &MockQRCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQRCodeRepository) EXPECT() *MockQRCodeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQRCodeRepository) Create(qrCode *domain.QRCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", qrCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQRCodeRepositoryMockRecorder) Create(qrCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQRCodeRepository)(nil).Create), qrCode)
}

// DeleteExpired mocks base method.
func (m *MockQRCodeRepository) DeleteExpired() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockQRCodeRepositoryMockRecorder) DeleteExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockQRCodeRepository)(nil).DeleteExpired))
}

// FindByCode mocks base method.
func (m *MockQRCodeRepository) FindByCode(code string) (*domain.QRCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", code)
	ret0, _ := ret[0].(*domain.QRCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockQRCodeRepositoryMockRecorder) FindByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockQRCodeRepository)(nil).FindByCode), code)
}

// FindByID mocks base method.
func (m *MockQRCodeRepository) FindByID(id uuid.UUID) (*domain.QRCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domain.QRCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockQRCodeRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockQRCodeRepository)(nil).FindByID), id)
}

// ListByUserID mocks base method.
func (m *MockQRCodeRepository) ListByUserID(userID uuid.UUID, offset, limit int) ([]*domain.QRCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", userID, offset, limit)
	ret0, _ := ret[0].([]*domain.QRCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockQRCodeRepositoryMockRecorder) ListByUserID(userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockQRCodeRepository)(nil).ListByUserID), userID, offset, limit)
}

// Update mocks base method.
func (m *MockQRCodeRepository) Update(qrCode *domain.QRCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", qrCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQRCodeRepositoryMockRecorder) Update(qrCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQRCodeRepository)(nil).Update), qrCode)
}
