// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/friendship.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/friendship.go -destination=internal/domain/mock/mock_friendship_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/gity/point-system/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFriendshipRepository is a mock of FriendshipRepository interface.
type MockFriendshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFriendshipRepositoryMockRecorder
	isgomock struct{}
}

// MockFriendshipRepositoryMockRecorder is the mock recorder for MockFriendshipRepository.
type MockFriendshipRepositoryMockRecorder struct {
	mock *MockFriendshipRepository
}

// NewMockFriendshipRepository creates a new mock instance.
func NewMockFriendshipRepository(ctrl *gomock.Controller) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{ctrl: ctrl}
	mock.recorder = &MockFriendshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendshipRepository) EXPECT() *MockFriendshipRepositoryMockRecorder {
	return m.recorder
}

// AreFriends mocks base method.
func (m *MockFriendshipRepository) AreFriends(userID1, userID2 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreFriends", userID1, userID2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreFriends indicates an expected call of AreFriends.
func (mr *MockFriendshipRepositoryMockRecorder) AreFriends(userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreFriends", reflect.TypeOf((*MockFriendshipRepository)(nil).AreFriends), userID1, userID2)
}

// Create mocks base method.
func (m *MockFriendshipRepository) Create(friendship *domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFriendshipRepositoryMockRecorder) Create(friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFriendshipRepository)(nil).Create), friendship)
}

// Delete mocks base method.
func (m *MockFriendshipRepository) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFriendshipRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFriendshipRepository)(nil).Delete), id)
}

// FindByID mocks base method.
func (m *MockFriendshipRepository) FindByID(id uuid.UUID) (*domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFriendshipRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFriendshipRepository)(nil).FindByID), id)
}

// FindByUsers mocks base method.
func (m *MockFriendshipRepository) FindByUsers(userID1, userID2 uuid.UUID) (*domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsers", userID1, userID2)
	ret0, _ := ret[0].(*domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsers indicates an expected call of FindByUsers.
func (mr *MockFriendshipRepositoryMockRecorder) FindByUsers(userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsers", reflect.TypeOf((*MockFriendshipRepository)(nil).FindByUsers), userID1, userID2)
}

// ListFriends mocks base method.
func (m *MockFriendshipRepository) ListFriends(userID uuid.UUID, offset, limit int) ([]*domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFriends", userID, offset, limit)
	ret0, _ := ret[0].([]*domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFriends indicates an expected call of ListFriends.
func (mr *MockFriendshipRepositoryMockRecorder) ListFriends(userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFriends", reflect.TypeOf((*MockFriendshipRepository)(nil).ListFriends), userID, offset, limit)
}

// ListPendingRequests mocks base method.
func (m *MockFriendshipRepository) ListPendingRequests(userID uuid.UUID, offset, limit int) ([]*domain.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingRequests", userID, offset, limit)
	ret0, _ := ret[0].([]*domain.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingRequests indicates an expected call of ListPendingRequests.
func (mr *MockFriendshipRepositoryMockRecorder) ListPendingRequests(userID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingRequests", reflect.TypeOf((*MockFriendshipRepository)(nil).ListPendingRequests), userID, offset, limit)
}

// Update mocks base method.
func (m *MockFriendshipRepository) Update(friendship *domain.Friendship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", friendship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFriendshipRepositoryMockRecorder) Update(friendship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFriendshipRepository)(nil).Update), friendship)
}
